In [ ]:
# Importing the necessary Python Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.formula.api import ols
from itertools import product

**1. RUN THE REGRESSION MODEL**

In [ ]:
# reading the csv file
car_data = pd.read_csv("auto.csv")

# listing the last five rows of tabular data
car_data.tail()

,mpg,cylinders,displacement,housepower,weight,acceleration,model year,origin,car name
393,27.0,4,140.0,86.00,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720,19.4,82,1,chevy s-10

In [ ]:
# Looking at the effects of weight and cylinders in miles per galon(mpg) and printing out the result
car_multi_reg = ols('mpg ~ weight + cylinders', data = car_data).fit()
print(car_multi_reg.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.696
Model:                            OLS   Adj. R-squared:                  0.695
Method:                 Least Squares   F-statistic:                     453.0
Date:                Thu, 09 Feb 2023   Prob (F-statistic):          5.68e-103
Time:                        00:05:36   Log-Likelihood:                -1145.4
No. Observations:                 398   AIC:                             2297.
Df Residuals:                     395   BIC:                             2309.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     46.3937      0.791     58.660      0.000      44.839      47.949
weight        -0.0064      0.001    -11.127      0.000      -0.008      -0.005
cylinders     -0.7025      0.287     -2.449      0.015      -1.267      -0.138
==============================================================================
Omnibus:                       44.285   Durbin-Watson:                   0.821
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               66.272
Skew:                           0.738   Prob(JB):                     4.07e-15
Kurtosis:                       4.348   Cond. No.                     1.13e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.13e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

**2. USING THE MODEL TO MAKE PREDICTIONS**

*2.1 Making the predictions using data from the original dataset*

In [ ]:
# Using .fittedvalues
print(car_multi_reg.fittedvalues)                         # Print out the fitted values
car_data['prediction'] = car_multi_reg.fittedvalues       # Create a column for the fitted values
car_data.head(5)

0      18.305112
1      17.093197
2      18.741145
3      18.760382
4      18.657786
         ...
393    25.693491
394    29.925576
395    28.867555
396    26.751512
397    26.142349
Length: 398, dtype: float64

,mpg,cylinders,displacement,housepower,weight,acceleration,model year,origin,car name,prediction
0,18.0,8,307.0,130.0,3504,12.0,70,1,chevrolet chevelle malibu,18.305112
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320,17.093197
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite,18.741145
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst,18.760382
4,17.0,8,302.0,140.0,3449,10.5,70,1,ford torino,18.657786

This is also equivalent to

In [ ]:
exp_orig = car_data[['weight','cylinders']]
main_pred = car_multi_reg.predict(exp_orig)
print(main_pred)

0      18.305112
1      17.093197
2      18.741145
3      18.760382
4      18.657786
         ...
393    25.693491
394    29.925576
395    28.867555
396    26.751512
397    26.142349
Length: 398, dtype: float64

In [ ]:
# Comparing the actual values and predicted values
compare = car_data[['mpg','prediction']]
compare

      mpg  prediction
0    18.0   18.305112
1    15.0   17.093197
2    18.0   18.741145
3    16.0   18.760382
4    17.0   18.657786
..    ...         ...
393  27.0   25.693491
394  44.0   29.925576
395  32.0   28.867555
396  28.0   26.751512
397  31.0   26.142349

[398 rows x 2 columns]

**3. THE RESIDUALS**

This is the difference between the actual value and the value predicted using the regression model.

In [ ]:
print(car_multi_reg.resid) # Calling the .resid on the actual regression model

0      -0.305112
1      -2.093197
2      -0.741145
3      -2.760382
4      -1.657786
         ...
393     1.306509
394    14.074424
395     3.132445
396     1.248488
397     4.857651
Length: 398, dtype: float64

We can also calculate this manually

In [ ]:
# This is the real actual response variable 'mpg' minus the predictions from the fitted value
print(car_data['mpg'] - car_multi_reg.fittedvalues)

0      -0.305112
1      -2.093197
2      -0.741145
3      -2.760382
4      -1.657786
         ...
393     1.306509
394    14.074424
395     3.132445
396     1.248488
397     4.857651
Length: 398, dtype: float64

**4. LOOKING AT THE MODEL'S FITNESS**

This shows how well our model, with its estimated parameters, fits the data.

We are going to consider two measures of it here:

*4.1 R-Squared (Coefficent of determination)*: Measures the proportion of variance in the response variable that can be explained by the explanatory variable(s). It ranges from 0 (poor fit) to 1 (perfect fit). Therefore the closer it is to 1, the better our model's fitness.

*4.2 Residual standard error (RSE)*: This is equal to square root of mean squared error(MSE). It is the difference between the observed response and the prediction. The smaller it is the better.

In [ ]:
# Calculating the R-Squared
print(car_multi_reg.rsquared)

0.6964013933838316

The result shows that about 69% of the variation in our response variable (mpg) can be explained by our explanatory variables (weight and cylinders)

In [ ]:
print(car_multi_reg.rsquared_adj)

0.6948641852490661

In [ ]:
# Calculating the RSE
mse = car_multi_reg.mse_resid
rse = np.sqrt(mse)
print(rse)

4.317479375332979

This means that the difference between the actual mpg and predicted mpg is about 4.32.