# **Python Modules, Packages and Libraries**

**A module** is a file containing Python code that defines functions, variables, and classes. They help to group related functions together, and their contents can be imported and used in other python scripts.

It is a single Python script (a .py file) that contains Python code.

In [ ]:
def greet(name):                          # This is a python function with one argument 'name'
    return f"Welcome to {name}!"          # f-string (formatted string)

greet("QMSS")

'Welcome to QMSS!'

In [1]:
import testing_module

message = testing_module.greet("The univerity of Michigan")
message

'Welcome to The univerity of Michigan!'

In [2]:
import testing_module as tm

message = tm.greet("LSA")
message

'Welcome to LSA!'

**A package** is a collection of related Python modules grouped together in a directory.

In [ ]:
#   mypackage/
#   ├── __init__.py
#   ├── module1.py
#   ├── module2.py
#   └── subpackage/
#    ├── __init__.py
#    └── module3.py

In [ ]:
# import mypackage.module1
# import mypackage.subpackage.module3

# result1 = mypackage.module1.function1()
# result2 = mypackage.subpackage.module3.function2()

**A library** is a collection of related modules and functions that serve a specific domain or purpose. It typically consists of multiple modules bundled together for a common use case.

Thus, it is imported and treated like a module.

# Keywords
In Python, keywords (also known as reserved words) are special words that have predefined meanings and are part of the language's syntax. These words are reserved for specific purposes and cannot be used as identifiers (e.g., variable names or function names) in your Python programs

In [3]:
import keyword

print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']

# **Variables and Data Structures**

Major Variable Types in Python

In [7]:
#INTEGERS: They are whole numbers.

Distance = 25

In [8]:
# FLOATS: Real numbers with decimal points.

time = 2.5

In [9]:
speed = Distance/time
speed

10.0

In [10]:
# STRING: Represents a sequence of characters.

course = 'QMSS'

In [11]:
# BOOLEAN: Represents truth values True and False.

is_clean = True

# **Data Structures in Python**

**LIST:** A built-in data structure that allows you to store and organize a collection of items.

They are ordered, indexed, mutable, and heterogeneous.

In [20]:
new_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
first_element = new_list[0]       # Access the first element (1)
sublist = new_list[2:4]           # Create a sublist [3, 4]

sublist

[3, 4]

In [21]:
length = len(new_list)
length

9

In [22]:
new_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
# Appending a list
new_list.append(10)
new_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [24]:
# adding a list to another
new_list.extend([11, 12])
new_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [25]:
# Inserting an element into a list
new_list.insert(3, 13)    # It inserts 13 in the third index
new_list

[1, 2, 3, 13, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [26]:
# Removing an element in a list
new_list.remove(2)  # Removed the first 2 in the list
new_list

[1, 3, 13, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [27]:
# Removing a list element by index
new_list.pop(0)
new_list

[3, 13, 4, 5, 6, 7, 8, 9, 10, 11, 12]

**DICTIONARY**: A Python dictionary is an unordered collection of key-value pairs.

It is a versatile data structure that allows us to store, retrieve, and manipulate data efficiently.

In [28]:
# Creating a dictionary. Student is a dictionary with 6 key-value pairs.
student = {
    'name': 'Kelvin',
    'major': 'Pol Sci',
    'level': 'Senior',
    'age': 22,
    'grade': 'A',
    'is_student': True
}

In [29]:
# Accessing the value of a dictionary

# Accessing values
print("Name:", student['name'])
print("Age:", student['age'])

Name: Kelvin
Age: 22

In [30]:
# Modifying the values

# Modifying values
student['major'] = 'Economics'
student['grade'] = 'B'
student['age'] = 24

student

{'name': 'Kelvin',
 'major': 'Economics',
 'level': 'Senior',
 'age': 24,
 'grade': 'B',
 'is_student': True}

In [31]:
# Adding and removing key-value pairs

student['state'] = 'Michigan'   # Add a new key-value pair
student.pop('is_student')       # Removing a key-value pair
student

{'name': 'Kelvin',
 'major': 'Economics',
 'level': 'Senior',
 'age': 24,
 'grade': 'B',
 'state': 'Michigan'}

In [32]:
# Checking if a key exist in a dictionary
if 'major' in student:
    print("Major exists in the dictionary.")

Major exists in the dictionary.

In [33]:
# The value can also be a list

Income_data = {'Name': ['Kelvin', 'Korede', 'Alex'],
        'Income': [100000, 120000, 55000]}
Income_data

{'Name': ['Kelvin', 'Korede', 'Alex'], 'Income': [100000, 120000, 55000]}

**Dataframe:** A DataFrame is a two-dimensional, tabular data structure commonly used in Python for data manipulation and analysis.

It is particularly associated with the **pandas** library.

In [ ]:
# DATAFRAME
import pandas as pd

# Creating a dataframe from a dictionary

Income_data = {'Name': ['Kelvin', 'Korede', 'Alex'],
        'Income': [100000, 120000, 55000]}

Income_df = pd.DataFrame(Income_data)
Income_df

     Name  Income
0  Kelvin  100000
1  Korede  120000
2    Alex   55000

In [ ]:
# Creating dataframe from list

names = ['Charles', 'Yoyo', 'Nick']
ages = [25, 30, 22]
age_df = pd.DataFrame({'Name': names, 'Age': ages})
age_df

      Name  Age
0  Charles   25
1     Yoyo   30
2     Nick   22

In [ ]:
# Read in from an external source

# Since dataframe is associated with pandas, we will treat it more when loking at pandas.

(3000, 9)

**Next:** We will be taking a look at three libraries that are very important for data manipulation, wrangling and visualization. Numpy, Pandas and Matplotlib.

The first two will be covered in class while the last one will be covered in the next lab.